###############################################################
# Program:
#     Week 10, MAP
#     Brother Ercanbrack, CS235
# Author:
#     Nimesh Subedi
# Summary:
#     MAP
# Time:
#     it took me about 7 hours to finish the project.
###############################################################

a.out: week10.o
	g++ -o a.out week10.o -std=c++11
	tar -cf week10.tar *.h *.cpp makefile

week10.o: map.h week10.cpp
	g++ -c week10.cpp -std=c++11
